name: 'C++ CI + Release'

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies (Boost, gh)
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev gh

      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON

      - name: Build project
        run: cmake --build .

      - name: Package as .deb
        run: cmake --build . --target package

      - name: Create GitHub Release using gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          VERSION=${{ github.run_number }}
          RELEASE_NAME="Release $VERSION"
          PACKAGE_PATH="./ip_filter-0.0.${VERSION}-Linux.deb"

          gh release create "$VERSION" "$PACKAGE_PATH" \
            --title "$RELEASE_NAME" \
            --notes "Автоматически созданный релиз" \
            --repo "${{ github.repository }}"
